version: 0.0
os: linux

files:
  - source: ./
    destination: /var/www/release/

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.bash
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.bash
      runas: root
    - location: scripts/start_server
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      runas: root